### ISSUE TITLE
Install fails on windows 7 - 64 bit : "OSError: currently only Windows and OSX are supported."

### ISSUE THREAD

**Issue by LouNo277** [ZoomerAnalytics/xlwings#160]
Hi Felix,
Thanks for your continued great work on this project, xlwings has made my interactions with numerous spreadsheets a lot easier.

However, I've been trying to install the latest release on my win7 PC, but so far I have not been successful. The "OSError: currently only Windows and OSX are supported" is raised every time I run 'setup.py install':

`Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    raise OSError("currently only Windows and OSX are supported.")
OSError: currently only Windows and OSX are supported.`

I have tried to comment-out the exception handler (replaced with 'pass'), and then the installation runs to the point where it tries to copy the dll but cannot find the file:

`byte-compiling C:\Users\u823003\Portable Python 2.7.6.1\App\Lib\site-packages\xlwings\_xlwindows.py to _xlwindows.pyc
byte-compiling C:\Users\u823003\Portable Python 2.7.6.1\App\Lib\site-packages\xlwings\__init__.py to __init__.pyc`
`running install_data`
`error: can't copy 'xlwings32.dll': doesn't exist or not a regular file`

I'd be grateful for your help with this. Many Thanks,
Louisa

**Comment by fzumstein** [comment]
Oh dear, thanks for reporting - this is now corrected with v0.3.4. Let me know if you run into any other issues! Closed by 2770cfd77698c2df0c35a461fc668d99103eb44e

**Comment by LouNo277** [comment]
Thanks for looking into it so quickly, sadly I still get the "can't copy
xlwings32.dll' does not exist" error...

**Comment by fzumstein** [comment]
how are you installing it? do you use pip?

Am Montag, 9. März 2015 schrieb Winnie_bluesky :

> Thanks for looking into it so quickly, sadly I still get the "can't copy
> xlwings32.dll' does not exist" error...
>
>
> On 9 March 2015 at 14:36, Felix Zumstein <notifications@github.com

**Comment by LouNo277** [comment]
No, I don't have pip on the windows PC ... I have copied the directory into
'site-packages' and then I run 'python setup.py install' from within.

Using pip on my mac worked fine, no issues there :)

**Comment by fzumstein** [comment]
You should not copy it into site-packages. Just unpack (anywhere, e.g. your desktop), `cd` into the unpacked directory and run `python setup.py install` - this will copy the files into the correct folders.

**Comment by LouNo277** [comment]
Hm, does not seem to make any difference, but I assume it might come down
to the python distribution beiing a portable version (?) :

`C:\Users\u823003\Downloads>cd xlwings-master`

`C:\Users\u823003\Downloads\xlwings-master>python setup.py install`
`C:\Users\u823003\Portable Python 2.7.6.1\App\lib\distutils\dist.py:267:
UserWarning: Unknown distribution option: 'install_requires'`
`  warnings.warn(msg)`
`running install`
`running build`
`running build_py`
`creating build`
`creating build\lib`
`creating build\lib\xlwings`
`copying xlwings\constants.py -> build\lib\xlwings`
`copying xlwings\main.py -> build\lib\xlwings`
`copying xlwings\server.py -> build\lib\xlwings`
`copying xlwings\utils.py -> build\lib\xlwings`
`copying xlwings\_xlmac.py -> build\lib\xlwings`
`copying xlwings\_xlwindows.py -> build\lib\xlwings`
`copying xlwings\__init__.py -> build\lib\xlwings`
`creating build\lib\xlwings\tests`
`copying xlwings\tests\test_xlwings.py -> build\lib\xlwings\tests`
`copying xlwings\tests\__init__.py -> build\lib\xlwings\tests`
`copying xlwings\xlwings.bas -> build\lib\xlwings`
`copying xlwings\tests\test_chart_1.xlsx -> build\lib\xlwings\tests`
`copying xlwings\tests\test_range_1.xlsx -> build\lib\xlwings\tests`
`copying xlwings\tests\test_workbook_1.xlsx -> build\lib\xlwings\tests`
`copying xlwings\xlwings_template.xltm -> build\lib\xlwings`
`running install_lib`
`running install_data`
`error: can't copy 'xlwings32.dll': doesn't exist or not a regular file`

**Comment by fzumstein** [comment]
ah - are you downloading the source from github? you need to download it from PyPI - github source doesn't include the dlls.

**Comment by LouNo277** [comment]
ok, that worked, thanks for your help!
